name: Rdoc CI

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
      - "*-stable"
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Specs ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Appraisal.root.gemfile
      KJ_FRAMEWORK_MATRIX_GEM: ${{ matrix.KJ_FRAMEWORK_MATRIX_GEM || '' }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        rubygems:
          - default
        bundler:
          - default
        framework:
          - framework_version: "6.11"
            appraisal: "rdoc-6-11"
            KJ_FRAMEWORK_MATRIX_GEM: "rdoc"
          - framework_version: "7.0+"
            appraisal: "rdoc-7-0-plus"

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: true

      - name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}"
        id: bundleAppraisalAttempt1
        run: bundle exec appraisal ${{ matrix.framework.appraisal }} install
        continue-on-error: true

      - name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}"
        id: bundleAppraisalAttempt2
        if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' }}
        run: bundle exec appraisal ${{ matrix.framework.appraisal }} install

      - name: Tests for ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}
        run: bundle exec appraisal ${{ matrix.framework.appraisal }} bundle exec kettle-test
