name: Rdoc CI

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
      - "*-stable"
    tags:
      - "!*" # Do not execute on tags
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    name: Specs ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/Appraisal.root.gemfile
      KJ_FRAMEWORK_MATRIX_GEM: ${{ matrix.KJ_FRAMEWORK_MATRIX_GEM || '' }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.2"
          - "3.3"
          - "3.4"
        rubygems:
          - default
        bundler:
          - default
        framework:
          - framework_version: "6.11"
            appraisal: "rdoc-6-11"
            KJ_FRAMEWORK_MATRIX_GEM: "rdoc"
          - framework_version: "7.0+"
            appraisal: "rdoc-7-0-plus"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: "${{ matrix.ruby }}"
          rubygems: "${{ matrix.rubygems }}"
          bundler: "${{ matrix.bundler }}"
          bundler-cache: ${{ matrix.ruby != 'ruby-2.4' && matrix.ruby != 'ruby-2.5' && matrix.ruby != 'ruby-2.6' && matrix.ruby != 'ruby-2.7' && matrix.ruby != 'truffleruby-25.0' && matrix.ruby != 'jruby-9.2' && matrix.ruby != 'jruby-9.3' }}

      - name: Bundle install for legacy Ruby engine
        if: ${{ matrix.ruby == 'ruby-2.4' || matrix.ruby == 'ruby-2.5' || matrix.ruby == 'ruby-2.6' || matrix.ruby == 'ruby-2.7' || matrix.ruby == 'truffleruby-25.0' || matrix.ruby == 'jruby-9.2' || matrix.ruby == 'jruby-9.3' }}
        run: |
          bundle config set --local path "${RUNNER_TEMP}/bundle"
          bundle config set --local mirror.https://gem.coop https://rubygems.org
          bundle install --jobs 1

      - name: "[Attempt 1] Appraisal for ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}"
        id: bundleAppraisalAttempt1
        run: bundle exec appraisal ${{ matrix.framework.appraisal }} install
        continue-on-error: true

      - name: "[Attempt 2] Appraisal for ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}"
        id: bundleAppraisalAttempt2
        if: ${{ steps.bundleAppraisalAttempt1.outcome == 'failure' }}
        run: bundle exec appraisal ${{ matrix.framework.appraisal }} install

      - name: Restore RSpec status log
        if: ${{!env.ACT}}
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: .rspec_status
          key: rspec-status-framework-ci-${{matrix.ruby}}-${{matrix.framework.appraisal}}-${{hashFiles('**/Gemfile.lock','Appraisal.root.gemfile','gemfiles/**/*.gemfile')}}-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            rspec-status-framework-ci-${{matrix.ruby}}-${{matrix.framework.appraisal}}-${{hashFiles('**/Gemfile.lock','Appraisal.root.gemfile','gemfiles/**/*.gemfile')}}-
            rspec-status-framework-ci-${{matrix.ruby}}-${{matrix.framework.appraisal}}-

      - name: Tests for ${{ matrix.ruby }}@${{ matrix.framework.framework_version }}
        run: bundle exec appraisal ${{ matrix.framework.appraisal }} bundle exec kettle-test
